### ISSUE TITLE
Data lengths do not match

### ISSUE THREAD

**Issue by adrian-jaques-b** [dongpng/cad_naacl2021#1]
Hello,

before I start I want to thank you for sharing your great work!

I would like to use your dataset to do some comparable classification tasks with other models and just checked your data. 
Unfortunately, I came across the issue that the lengths of the provided splits do not match the length of the sum of the splits from the whole dataset, when I extract them myself:

![image](https://user-images.githubusercontent.com/68905111/182862804-adce5da0-c555-454e-835c-12cb4f6b2374.png)

The cad_v1 and the cad_v1_1 show the exact same length. 
Do you know what the problem might is? Am I doing something wrong?

Thank you! 
Kind regards,
Jaqu

**Comment by dongpng** [comment]
Hi,

Yes, there's some additional processing involved. Given the full file, we can generate individual files for each split (containing id, text, labels) using:

````
python classification_util.py write_splits --input_file="../data/cad_v1.tsv"
````

So start with the provided splits, unless you want to change some of the pre-processing.

**Comment by adrian-jaques-b** [comment]
Okay now it's clear to me. 
Thank you so much!
