### ISSUE TITLE
Question regarding the data

### ISSUE THREAD

**Issue by adrian-jaques-b** [dongpng/cad_naacl2021#2]
Hello and thank you for sharing your work. 
I find your approach really interesting and I would like use your data for own experiments. 

In the paper you used just the primary classes for the classification task. 
Howerever, after skipping through the data I realised that some texts have multiple labels. 

![image](https://user-images.githubusercontent.com/68905111/224335319-c12ea472-2613-4520-96a3-8d61eb5a3bcb.png)

I just wanted to ask how you dealt with this multiple labels. Did you exclude the data rows with multiple labels or did you just take them as they are?

Thank you so much und kind regards
Jaqu

**Comment by dongpng** [comment]
We take all labels for a particular instance, i.e. we treat this as a multi-label classification problem.

Best,
Dong
